/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { motion } from "framer-motion-3d";
import { easing } from "maath";
import React, { useRef } from "react";
import * as THREE from "three";
import { useSnapshot } from "valtio";
import { state } from "./proxy/store";

export function Can(props) {
  const { nodes, materials } = useGLTF("/project.glb");
  let ref = useRef();
  let snap = useSnapshot(state);
  const texture = useTexture(snap.SelectedTexture);
  // Configurer les propriétés de la texture
  texture.wrapS = THREE.RepeatWrapping;
  texture.wrapT = THREE.RepeatWrapping;
  texture.repeat.set(1, 1);
  texture.rotation = -3.2;

  useFrame((state, delta) => {
    easing.dampE(
      ref.current.rotation,
      [state.pointer.y / 5, -state.pointer.x / 5, 0],
      0.5,
      delta
    );
  });

  return (
    <motion.group
      initial={{ y: -10 }}
      animate={{ y: 0 }}
      transition={{ ease: "backOut", duration: 1 }}
      ref={ref}
      scale={0.2}
      position={[0.5, -0.1, 0]}
      {...props}
      dispose={null}
    >
      <motion.group
        key={snap.SelectedTexture}
        initial={{ rotateY: 10 }}
        animate={{ rotateY: 0 }}
        transition={{ ease: "easeOut", duration: 1 }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0.geometry}
          material={materials.water}
          position={[0.002, 0, -0.929]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group position={[0.002, 0, -0.929]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_1.geometry}
            material={materials.Metallic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_1_1.geometry}
            material={nodes.mesh_1_1.material}
          >
            <meshBasicMaterial map={texture} />
          </mesh>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_2.geometry}
          material={materials.water}
          position={[0.002, 0, -0.929]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </motion.group>
    </motion.group>
  );
}

useGLTF.preload("/project.glb");
[
  "test.png",
  "/cans/grape_can.png",
  "/cans/apple_can.png",
  "/cans/blue_can.png",
  "/cans/mango_can.png",
  "/cans/tropical_can.png",
  "/cans/cosmic_can.png",
].forEach(useTexture.preload);
