/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { motion } from "framer-motion-3d";
import { easing } from "maath";
import React, { useRef } from "react";
import { useSnapshot } from "valtio";
import { state } from "./proxy/store";

export function Can(props) {
  const { nodes, materials } = useGLTF("/project.glb");
  let ref = useRef();
  let snap = useSnapshot(state);
  const texture = useTexture(snap.SelectedTexture);

  useFrame((state, delta) => {
    easing.dampE(
      ref.current.rotation,
      [state.pointer.y / 5, -state.pointer.x / 10, 0],
      0.5,
      delta
    );
  });

  return (
    <motion.group
      ref={ref}
      scale={0.2}
      position={[0.5, -0.2, 0]}
      {...props}
      dispose={null}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={materials.water}
        position={[0.003, 0, 0.93]}
        rotation={[-Math.PI / 2, 0, 0]}
      ></mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_1.geometry}
        material={materials.Metallic}
        position={[-0.002, 0, 0.914]}
        rotation={[-Math.PI / 2, 0, 0]}
      ></mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_2.geometry}
        material={materials.water}
        position={[0.003, 0, 0.93]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </motion.group>
  );
}

useGLTF.preload("/project.glb");
[
  "/cans/grape_can.png",
  "/cans/apple_can.png",
  "/cans/blue_can.png",
  "/cans/mango_can.png",
  "/cans/tropical_can.png",
  "/cans/cosmic_can.png",
].forEach(useTexture.preload);
